# Generated by Django 4.0.3 on 2022-03-25 00:11

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('blogs', models.ForeignKey(on_delete=builtins.callable, to='blogs.blog')),
            ],
        ),
    ]
