# Generated by Django 4.0.4 on 2022-05-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='catergory',
            new_name='category',
        ),
    ]
