# Generated by Django 4.0.4 on 2022-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('date_birth', models.DateField()),
                ('subject', models.ManyToManyField(to='contacts.category')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelForm',
        ),
    ]
