# Generated by Django 4.0.4 on 2022-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_frommodel_delete_modelform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frommodel',
            name='subject',
            field=models.ManyToManyField(blank=True, to='contacts.category'),
        ),
    ]
